######################################################################
# Automatically generated by qmake (2.01a) Wed Apr 14 21:58:28 2010
######################################################################

TEMPLATE = app
TARGET =
DEPENDPATH += .
INCLUDEPATH += . ../src/
CONFIG += qtestlib
DEFINES += WORKER_TEST

# Input
SOURCES += testworker.cpp ../src/worker.cpp
HEADERS += ../src/worker.h
