/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -c DbusIfAdaptor -a dbusifadaptor.h:dbusifadaptor.cpp com.balenet.flexo.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef DBUSIFADAPTOR_H_1274725511
#define DBUSIFADAPTOR_H_1274725511

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface com.balenet.flexo
 */
class DBusIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "com.balenet.flexo")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"com.balenet.flexo\">\n"
"    <method name=\"Activate\"/>\n"
"  </interface>\n"
        "")
public:
    DBusIfAdaptor(QObject *parent);
    virtual ~DBusIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Activate();
Q_SIGNALS: // SIGNALS
};

#endif
